dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.2.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'

dotenv: .env

# Information for how to deal with each network
networks:
  default: development
  rinkeby:
    verify: true # If we should verify the code onto etherscan, here yes
